import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";
import { useState, useEffect } from 'react'

const categories = {
  ultimateTriviaChallenge: {
    trivia: {
      categoryId: 9
    }
  },
  generalKnowledge: {
    mythology: {
      categoryId: 20
    },
    sports: {
      categoryId: 21
    },
    geography: {
      categoryId: 22
    },
    history: {
      categoryId: 23
    },
    politics: {
      categoryId: 24
    },
    art: {
      categoryId: 25
    },
    celebrities: {
      categoryId: 26
    },
    animals: {
      categoryId: 27
    },
    vehicles: {
      categoryId: 28
    }
  },
  entertainment: {
    books: {
      categoryId: 10
    },
    film: {
      categoryId: 11
    },
    music: {
      categoryId: 12
    },
    musicals: {
      categoryId: 13
    },
    television: {
      categoryId: 14
    },
    videogames: {
      categoryId: 15
    },
    boardgames: {
      categoryId: 16
    },
    comics: {
      categoryId: 29
    },
    anime: {
      categoryId: 31
    },
    cartoons: {
      categoryId: 32
    }
  },
  science: {
    sciences: {
      categoryId: 17
    },
    computers: {
      categoryId: 18
    },
    mathematics: {
      categoryId: 19
    },
    gadgets: {
      categoryId: 30
    }
  }
}

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  const router = useRouter();
  const logout = useLogout();
  const isLoggedIn = props.isLoggedIn
  const user = props.user
  const [scores, setScores] = useState([])

  useEffect(() => {
    async function fetchHighScores() {
      try {
        if (isLoggedIn && user) {
          const userId = user._id
          const res = await fetch(`/api/score/getAllScores?userId=${userId}`)
          if (res.status === 200) {
              const data = await res.json()
              setScores(data)
          } else {
              console.log("error getting highscores")
          }
        }
      } catch (err) {
          console.log(err.message)
      }
    }
    fetchHighScores()
  }, [isLoggedIn, user, scores])

  async function handleDeleteScore(e) {
    const category = e.target.value
    console.log(category)
    try {
        const res = await fetch("/api/score/removeScore", {
            method: "DELETE",
            headers: {
                "content-type": "application/json",
            },
            body: JSON.stringify({ category, userId }),
        })
        if (res.status === 200) {
            console.log('Score deleted successfully')
        } else {
            console.error('Error deleting score')
        }
    } catch (err) {
        console.log(err.message)
    }
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.main}>
      {isLoggedIn && (
        <section>
          <h2>{user.username}&apos;s High Scores</h2>
          <div>
            {Array.isArray(scores) && scores.length > 0 ? (
              scores.map((score) => (
                <>
                  <div key={score.category}>
                    <h4>{score.category.charAt(0).toUpperCase() + score.category.slice(1)}</h4>
                    <p>High Score: {score.highScore}</p>
                    <button onClick={handleDeleteScore} value={score.category}>Delete Score</button>
                  </div>
                </>
              ))
            ) : (
              <p>No High Scores Available</p>
            )}
          </div>
        </section>
      )}
        <h1>Categories</h1>
        <h2>Ultimate Trivia Challenge</h2>
        <div>
          {Object.keys(categories.ultimateTriviaChallenge).map((category) => (
            <button key={category.categoryId}>
              <Link href={`/trivia/${category}`}>
                Ultimate Trivia Challenge
              </Link>
            </button>
          ))}
        </div>
        <h2>General Knowledge</h2>
        <div>
          {Object.keys(categories.generalKnowledge).map((category) => (
            <button key={category.categoryId}>
              <Link href={`/trivia/${category}`}>
                {category.charAt(0).toUpperCase() + category.slice(1)}
              </Link>
            </button>
          ))}
        </div>
        <h2>Entertainment</h2>
        <div>
          {Object.keys(categories.entertainment).map((category) => (
            <button key={category.categoryId}>
              <Link href={`/trivia/${category}`}>
                {category.charAt(0).toUpperCase() + category.slice(1)}
              </Link>
            </button>
          ))}
        </div>
        <h2>Science</h2>
        <div>
          {Object.keys(categories.science).map((category) => (
            <button key={category.categoryId}>
              <Link href={`/trivia/${category}`}>
                {category.charAt(0).toUpperCase() + category.slice(1)}
              </Link>
            </button>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
