import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";

const categories = {
  ultimateTriviaChallenge: {
    general: {
      categoryId: 9
    }
  },
  generalKnowledge: {
    mythology: {
      categoryId: 20
    },
    sports: {
      categoryId: 21
    },
    geography: {
      categoryId: 22
    },
    history: {
      categoryId: 23
    },
    politics: {
      categoryId: 24
    },
    art: {
      categoryId: 25
    },
    celebrities: {
      categoryId: 26
    },
    animals: {
      categoryId: 27
    },
    vehicles: {
      categoryId: 28
    }
  },
  entertainment: {
    books: {
      categoryId: 10
    },
    film: {
      categoryId: 11
    },
    music: {
      categoryId: 12
    },
    musicals: {
      categoryId: 13
    },
    television: {
      categoryId: 14
    },
    videogames: {
      categoryId: 15
    },
    boardgames: {
      categoryId: 16
    },
    comics: {
      categoryId: 29
    },
    anime: {
      categoryId: 31
    },
    cartoons: {
      categoryId: 32
    }
  },
  science: {
    sciences: {
      categoryId: 17
    },
    computers: {
      categoryId: 18
    },
    mathematics: {
      categoryId: 19
    },
    gadgets: {
      categoryId: 30
    }
  }
}

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  const router = useRouter();
  const logout = useLogout();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.main}>
        <h2>Ultimate Trivia Challenge</h2>
        <div>
          {Object.keys(categories.ultimateTriviaChallenge).map((category) => (
            <button key={category.categoryId}>
              <Link href={`/trivia/${category}`}>
                Ultimate Trivia Challenge
              </Link>
            </button>
          ))}
        </div>
        <h2>General Knowledge</h2>
        <div>
          {Object.keys(categories.generalKnowledge).map((category) => (
            <button key={category.categoryId}>
              <Link href={`/trivia/${category}`}>
                {category}
              </Link>
            </button>
          ))}
        </div>
        <h2>Entertainment</h2>
        <div>
          {Object.keys(categories.entertainment).map((category) => (
            <button key={category.categoryId}>
              <Link href={`/trivia/${category}`}>
                {category}
              </Link>
            </button>
          ))}
        </div>
        <h2>Science</h2>
        <div>
          {Object.keys(categories.science).map((category) => (
            <button key={category.categoryId}>
              <Link href={`/trivia/${category}`}>
                {category}
              </Link>
            </button>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
